/**
 * Storage
 * Sphereon Storage APIs provide an abstraction layer for storage of containers (folders) and objects (files), using a filesystem backend or AWS-s3, Azure blobstorage or Google cloud storage backend.
 *
 * OpenAPI spec version: 0.7
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.sphereon.sdk.storage.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * ContainerRequest
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-04T03:49:14.058+01:00")
public class ContainerRequest   {
  /**
   * The way a container is creation. If the container should be new, is allowed already exist or use an existing remote container.
   */
  public enum CreationModeEnum {
    @SerializedName("NEW_ONLY")
    NEW_ONLY("NEW_ONLY"),
    
    @SerializedName("REQUIRE_EXISTING")
    REQUIRE_EXISTING("REQUIRE_EXISTING"),
    
    @SerializedName("ALLOW_EXISTING")
    ALLOW_EXISTING("ALLOW_EXISTING");

    private String value;

    CreationModeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("creationMode")
  private CreationModeEnum creationMode = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("backendId")
  private String backendId = null;

  public ContainerRequest creationMode(CreationModeEnum creationMode) {
    this.creationMode = creationMode;
    return this;
  }

   /**
   * The way a container is creation. If the container should be new, is allowed already exist or use an existing remote container.
   * @return creationMode
  **/
  @ApiModelProperty(example = "null", value = "The way a container is creation. If the container should be new, is allowed already exist or use an existing remote container.")
  public CreationModeEnum getCreationMode() {
    return creationMode;
  }

  public void setCreationMode(CreationModeEnum creationMode) {
    this.creationMode = creationMode;
  }

  public ContainerRequest name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ContainerRequest backendId(String backendId) {
    this.backendId = backendId;
    return this;
  }

   /**
   * The backend in which the container will be stored or is stored.
   * @return backendId
  **/
  @ApiModelProperty(example = "null", value = "The backend in which the container will be stored or is stored.")
  public String getBackendId() {
    return backendId;
  }

  public void setBackendId(String backendId) {
    this.backendId = backendId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContainerRequest containerRequest = (ContainerRequest) o;
    return Objects.equals(this.creationMode, containerRequest.creationMode) &&
        Objects.equals(this.name, containerRequest.name) &&
        Objects.equals(this.backendId, containerRequest.backendId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creationMode, name, backendId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContainerRequest {\n");
    
    sb.append("    creationMode: ").append(toIndentedString(creationMode)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    backendId: ").append(toIndentedString(backendId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

