/**
 * Storage
 * Sphereon Storage APIs provide an abstraction layer for storage of containers (folders) and objects (files), using a filesystem backend or AWS-s3, Azure blobstorage or Google cloud storage backend.
 *
 * OpenAPI spec version: 0.7
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Storage);
  }
}(this, function(expect, Storage) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Storage.RequestCredentials();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RequestCredentials', function() {
    it('should create an instance of RequestCredentials', function() {
      // uncomment below and update the code to test RequestCredentials
      //var instane = new Storage.RequestCredentials();
      //expect(instance).to.be.a(Storage.RequestCredentials);
    });

    it('should have the property credentialType (base name: "credentialType")', function() {
      // uncomment below and update the code to test the property credentialType
      //var instane = new Storage.RequestCredentials();
      //expect(instance).to.be();
    });

    it('should have the property oauth2Credentials (base name: "oauth2Credentials")', function() {
      // uncomment below and update the code to test the property oauth2Credentials
      //var instane = new Storage.RequestCredentials();
      //expect(instance).to.be();
    });

    it('should have the property oauthCredentials (base name: "oauthCredentials")', function() {
      // uncomment below and update the code to test the property oauthCredentials
      //var instane = new Storage.RequestCredentials();
      //expect(instance).to.be();
    });

    it('should have the property usernamePasswordCredentials (base name: "usernamePasswordCredentials")', function() {
      // uncomment below and update the code to test the property usernamePasswordCredentials
      //var instane = new Storage.RequestCredentials();
      //expect(instance).to.be();
    });

  });

}));
