/* 
 * Storage
 *
 * Sphereon Storage APIs provide an abstraction layer for storage of containers (folders) and objects (files), using a filesystem backend or AWS-s3, Azure blobstorage or Google cloud storage backend.
 *
 * OpenAPI spec version: 0.6.0
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Sphereon.SDK.Storage.Model
{
    /// <summary>
    /// BackendRequest
    /// </summary>
    [DataContract]
    public partial class BackendRequest :  IEquatable<BackendRequest>
    {
        /// <summary>
        /// Gets or Sets AuthenticationProvider
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum AuthenticationProviderEnum
        {
            
            /// <summary>
            /// Enum APISUPPLIER for "API_SUPPLIER"
            /// </summary>
            [EnumMember(Value = "API_SUPPLIER")]
            APISUPPLIER,
            
            /// <summary>
            /// Enum ENDUSER for "END_USER"
            /// </summary>
            [EnumMember(Value = "END_USER")]
            ENDUSER
        }

        /// <summary>
        /// Gets or Sets BackendType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum BackendTypeEnum
        {
            
            /// <summary>
            /// Enum FILESYSTEM for "FILESYSTEM"
            /// </summary>
            [EnumMember(Value = "FILESYSTEM")]
            FILESYSTEM,
            
            /// <summary>
            /// Enum AMAZONS3 for "AMAZON_S3"
            /// </summary>
            [EnumMember(Value = "AMAZON_S3")]
            AMAZONS3,
            
            /// <summary>
            /// Enum MSAZUREBLOBSTORAGE for "MS_AZURE_BLOB_STORAGE"
            /// </summary>
            [EnumMember(Value = "MS_AZURE_BLOB_STORAGE")]
            MSAZUREBLOBSTORAGE,
            
            /// <summary>
            /// Enum GOOGLECLOUDSTORAGE for "GOOGLE_CLOUD_STORAGE"
            /// </summary>
            [EnumMember(Value = "GOOGLE_CLOUD_STORAGE")]
            GOOGLECLOUDSTORAGE
        }

        /// <summary>
        /// Gets or Sets AuthenticationProvider
        /// </summary>
        [DataMember(Name="authenticationProvider", EmitDefaultValue=false)]
        public AuthenticationProviderEnum? AuthenticationProvider { get; set; }
        /// <summary>
        /// Gets or Sets BackendType
        /// </summary>
        [DataMember(Name="backendType", EmitDefaultValue=false)]
        public BackendTypeEnum? BackendType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="BackendRequest" /> class.
        /// </summary>
        /// <param name="AuthenticationProvider">AuthenticationProvider.</param>
        /// <param name="SecretKey">SecretKey.</param>
        /// <param name="BackendType">BackendType.</param>
        /// <param name="Name">Name.</param>
        /// <param name="Description">Description.</param>
        /// <param name="ParentId">ParentId.</param>
        /// <param name="AccesskeyId">AccesskeyId.</param>
        public BackendRequest(AuthenticationProviderEnum? AuthenticationProvider = null, string SecretKey = null, BackendTypeEnum? BackendType = null, string Name = null, string Description = null, string ParentId = null, string AccesskeyId = null)
        {
            this.AuthenticationProvider = AuthenticationProvider;
            this.SecretKey = SecretKey;
            this.BackendType = BackendType;
            this.Name = Name;
            this.Description = Description;
            this.ParentId = ParentId;
            this.AccesskeyId = AccesskeyId;
        }
        
        /// <summary>
        /// Gets or Sets SecretKey
        /// </summary>
        [DataMember(Name="secretKey", EmitDefaultValue=false)]
        public string SecretKey { get; set; }
        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }
        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }
        /// <summary>
        /// Gets or Sets ParentId
        /// </summary>
        [DataMember(Name="parentId", EmitDefaultValue=false)]
        public string ParentId { get; set; }
        /// <summary>
        /// Gets or Sets AccesskeyId
        /// </summary>
        [DataMember(Name="accesskeyId", EmitDefaultValue=false)]
        public string AccesskeyId { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BackendRequest {\n");
            sb.Append("  AuthenticationProvider: ").Append(AuthenticationProvider).Append("\n");
            sb.Append("  SecretKey: ").Append(SecretKey).Append("\n");
            sb.Append("  BackendType: ").Append(BackendType).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  ParentId: ").Append(ParentId).Append("\n");
            sb.Append("  AccesskeyId: ").Append(AccesskeyId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as BackendRequest);
        }

        /// <summary>
        /// Returns true if BackendRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of BackendRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BackendRequest other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.AuthenticationProvider == other.AuthenticationProvider ||
                    this.AuthenticationProvider != null &&
                    this.AuthenticationProvider.Equals(other.AuthenticationProvider)
                ) && 
                (
                    this.SecretKey == other.SecretKey ||
                    this.SecretKey != null &&
                    this.SecretKey.Equals(other.SecretKey)
                ) && 
                (
                    this.BackendType == other.BackendType ||
                    this.BackendType != null &&
                    this.BackendType.Equals(other.BackendType)
                ) && 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                ) && 
                (
                    this.Description == other.Description ||
                    this.Description != null &&
                    this.Description.Equals(other.Description)
                ) && 
                (
                    this.ParentId == other.ParentId ||
                    this.ParentId != null &&
                    this.ParentId.Equals(other.ParentId)
                ) && 
                (
                    this.AccesskeyId == other.AccesskeyId ||
                    this.AccesskeyId != null &&
                    this.AccesskeyId.Equals(other.AccesskeyId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.AuthenticationProvider != null)
                    hash = hash * 59 + this.AuthenticationProvider.GetHashCode();
                if (this.SecretKey != null)
                    hash = hash * 59 + this.SecretKey.GetHashCode();
                if (this.BackendType != null)
                    hash = hash * 59 + this.BackendType.GetHashCode();
                if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                if (this.Description != null)
                    hash = hash * 59 + this.Description.GetHashCode();
                if (this.ParentId != null)
                    hash = hash * 59 + this.ParentId.GetHashCode();
                if (this.AccesskeyId != null)
                    hash = hash * 59 + this.AccesskeyId.GetHashCode();
                return hash;
            }
        }
    }

}
