/* 
 * Storage
 *
 * Sphereon Storage APIs provide an abstraction layer for storage of containers (folders) and objects (files), using a filesystem backend or AWS-s3, Azure blobstorage or Google cloud storage backend.
 *
 * OpenAPI spec version: 0.8
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sphereon.SDK.Storage.Api;
using Sphereon.SDK.Storage.Model;
using Sphereon.SDK.Storage.Client;
using System.Reflection;

namespace Sphereon.SDK.Storage.Test
{
    /// <summary>
    ///  Class for testing StreamLocation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StreamLocationTests
    {
        // TODO uncomment below to declare an instance variable for StreamLocation
        //private StreamLocation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StreamLocation
            //instance = new StreamLocation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StreamLocation
        /// </summary>
        [Test]
        public void StreamLocationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StreamLocation
            //Assert.IsInstanceOfType<StreamLocation> (instance, "variable 'instance' is a StreamLocation");
        }

        /// <summary>
        /// Test the property 'FolderPath'
        /// </summary>
        [Test]
        public void FolderPathTest()
        {
            // TODO unit test for the property 'FolderPath'
        }
        /// <summary>
        /// Test the property 'Filename'
        /// </summary>
        [Test]
        public void FilenameTest()
        {
            // TODO unit test for the property 'Filename'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ContainerId'
        /// </summary>
        [Test]
        public void ContainerIdTest()
        {
            // TODO unit test for the property 'ContainerId'
        }
        /// <summary>
        /// Test the property 'OriginalFilename'
        /// </summary>
        [Test]
        public void OriginalFilenameTest()
        {
            // TODO unit test for the property 'OriginalFilename'
        }

    }

}
