/* 
 * Storage
 *
 * Sphereon Storage APIs provide an abstraction layer for storage of containers (folders) and objects (files), using a filesystem backend or AWS-s3, Azure blobstorage or Google cloud storage backend.
 *
 * OpenAPI spec version: 0.8
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sphereon.SDK.Storage.Api;
using Sphereon.SDK.Storage.Model;
using Sphereon.SDK.Storage.Client;
using System.Reflection;

namespace Sphereon.SDK.Storage.Test
{
    /// <summary>
    ///  Class for testing InfoResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InfoResponseTests
    {
        // TODO uncomment below to declare an instance variable for InfoResponse
        //private InfoResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InfoResponse
            //instance = new InfoResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InfoResponse
        /// </summary>
        [Test]
        public void InfoResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InfoResponse
            //Assert.IsInstanceOfType<InfoResponse> (instance, "variable 'instance' is a InfoResponse");
        }

        /// <summary>
        /// Test the property 'StreamInfos'
        /// </summary>
        [Test]
        public void StreamInfosTest()
        {
            // TODO unit test for the property 'StreamInfos'
        }

    }

}
